#!/usr/bin/env python3
"""Add notification string keys to all non-English locale files."""

import os

translations = {
    "nb": {
        "notif.generic.checkin.title": "✅ Rask sjekk",
        "notif.generic.checkin.body": "Noe forbruk i dag? Trykk for å logge det mens det er friskt i minnet.",
        "notif.generic.moneynotes.title": "Pengenotater 💰",
        "notif.generic.moneynotes.body": "Beste tidspunkt å logge er rett etter du har brukt penger. Nest best? Nå.",
        "notif.generic.dontforget.title": "🔔 Ikke glem",
        "notif.generic.dontforget.body": "Små vaner, stor klarhet. Bruk 30 sekunder på å logge i dag.",
        "notif.generic.logday.title": "Logg dagen din 📋",
        "notif.generic.logday.body": "Fremtidige deg vil takke deg. Noe å legge til?",
        "notif.generic.stayontrack.title": "Hold deg på sporet 🎯",
        "notif.generic.stayontrack.body": "Å holde oversikten tar sekunder. Budsjettet ditt vil takke deg.",
        "notif.generic.open.title": "Åpne Notyfi 👀",
        "notif.generic.open.body": "Fang dagens forbruk mens det fortsatt er friskt i minnet.",
        "notif.generic.journaltime.title": "📝 Journaltid",
        "notif.generic.journaltime.body": "En rask logg nå sparer mye gjetting senere.",
        "notif.generic.whatdidyouspend.title": "Hva brukte du? 🤔",
        "notif.generic.whatdidyouspend.body": "Lommeboken husker alt. Hjernen din gjør ikke det. Logg nå 👇",
        "notif.streak.days.title": "🔥 %d dager på rad",
        "notif.streak.consistent.body": "Du har vært konsekvent 💪 Hold rekken i live i dag.",
        "notif.streak.roll.title": "På god vei 🚀",
        "notif.streak.roll.body": "%d dager med logging. I dag blir %d.",
        "notif.budget.nearlygone.title": "Budsjettet er nesten brukt opp ⚠️",
        "notif.budget.nearlygone.body": "%d%% brukt. Bare %@ igjen denne måneden.",
        "notif.budget.almostover.title": "🚨 Nesten over budsjettet",
        "notif.budget.almostover.body": "%@ igjen med %d dager å gå. Vær forsiktig.",
        "notif.budget.check.title": "Budsjettsjekk 📊",
        "notif.budget.check.body": "Du har brukt %d%% denne måneden. %@ igjen over %d dager.",
        "notif.budget.lookinggood.title": "Ser bra ut 👍",
        "notif.budget.lookinggood.body": "%@ igjen med %d dager tilbake. Du er på rett spor ✅",
        "notif.category.overtarget.title": "%@ over mål 📈",
        "notif.category.overtarget.body": "Du er på %d%% av %@-guiden din denne måneden.",
        "notif.category.almostcap.title": "⚡ %@ nesten ved taket",
        "notif.category.almostcap.body": "%d%% av %@-guiden brukt. %@ igjen.",
        "notif.savings.hit.title": "🎉 Sparemål nådd!",
        "notif.savings.hit.body": "Du har nådd sparemålet ditt denne måneden. Godt jobbet 🌟",
        "notif.savings.almost.title": "Nesten ved sparemålet 💪",
        "notif.savings.almost.body": "Bare %@ unna å nå målet ditt.",
        "notif.recurring.today": "i dag",
        "notif.recurring.tomorrow": "i morgen",
        "notif.recurring.indays": "om %d dager",
        "notif.recurring.title": "🔁 Kommende belastning %@",
        "notif.recurring.body": "%@ på %@ forfaller %@.",
        "notif.weekly.title": "Siste 7 dager 📅",
        "notif.weekly.body": "Du har logget %@ i utgifter den siste uken.",
        "notif.missed.title": "😴 I går ikke logget",
        "notif.missed.body": "Ingenting logget for i går — vil du legge til noe fra hukommelsen?",
    },
    "da": {
        "notif.generic.checkin.title": "✅ Hurtig tjek",
        "notif.generic.checkin.body": "Noget forbrug i dag? Tryk for at logge det mens det er friskt.",
        "notif.generic.moneynotes.title": "Pengenoter 💰",
        "notif.generic.moneynotes.body": "Det bedste tidspunkt at logge er lige efter forbrug. Næstbedst? Nu.",
        "notif.generic.dontforget.title": "🔔 Glem ikke",
        "notif.generic.dontforget.body": "Små vaner, stor klarhed. Brug 30 sekunder på at logge i dag.",
        "notif.generic.logday.title": "Log din dag 📋",
        "notif.generic.logday.body": "Dit fremtidige jeg vil takke dig. Noget at tilføje?",
        "notif.generic.stayontrack.title": "Hold sporet 🎯",
        "notif.generic.stayontrack.body": "At holde styr på det tager sekunder. Dit budget vil takke dig.",
        "notif.generic.open.title": "Åbn Notyfi 👀",
        "notif.generic.open.body": "Fang dagens forbrug mens det stadig er friskt i hukommelsen.",
        "notif.generic.journaltime.title": "📝 Journaltid",
        "notif.generic.journaltime.body": "En hurtig log nu sparer meget gætteri senere.",
        "notif.generic.whatdidyouspend.title": "Hvad brugte du? 🤔",
        "notif.generic.whatdidyouspend.body": "Din pung husker alt. Din hjerne gør ikke. Log nu 👇",
        "notif.streak.days.title": "🔥 %d dage i træk",
        "notif.streak.consistent.body": "Du har været konsekvent 💪 Hold rækken i live i dag.",
        "notif.streak.roll.title": "På vej 🚀",
        "notif.streak.roll.body": "%d dages logning. I dag bliver %d.",
        "notif.budget.nearlygone.title": "Budgettet er næsten brugt ⚠️",
        "notif.budget.nearlygone.body": "%d%% brugt. Kun %@ tilbage denne måned.",
        "notif.budget.almostover.title": "🚨 Næsten over budgettet",
        "notif.budget.almostover.body": "%@ tilbage med %d dage tilbage. Vær forsigtig.",
        "notif.budget.check.title": "Budgettjek 📊",
        "notif.budget.check.body": "Du har brugt %d%% denne måned. %@ tilbage over %d dage.",
        "notif.budget.lookinggood.title": "Ser godt ud 👍",
        "notif.budget.lookinggood.body": "%@ tilbage med %d dage tilbage. Du er på rette spor ✅",
        "notif.category.overtarget.title": "%@ over målet 📈",
        "notif.category.overtarget.body": "Du er på %d%% af din %@-guide denne måned.",
        "notif.category.almostcap.title": "⚡ %@ næsten ved grænsen",
        "notif.category.almostcap.body": "%d%% af din %@-guide brugt. %@ tilbage.",
        "notif.savings.hit.title": "🎉 Sparemålet nået!",
        "notif.savings.hit.body": "Du har nået dit sparemål denne måned. Godt klaret 🌟",
        "notif.savings.almost.title": "Næsten ved sparemålet 💪",
        "notif.savings.almost.body": "Kun %@ fra at nå dit mål.",
        "notif.recurring.today": "i dag",
        "notif.recurring.tomorrow": "i morgen",
        "notif.recurring.indays": "om %d dage",
        "notif.recurring.title": "🔁 Kommende opkrævning %@",
        "notif.recurring.body": "%@ for %@ forfalder %@.",
        "notif.weekly.title": "Sidste 7 dage 📅",
        "notif.weekly.body": "Du har logget %@ i udgifter i den seneste uge.",
        "notif.missed.title": "😴 I går ikke logget",
        "notif.missed.body": "Intet logget for i går — vil du tilføje noget fra hukommelsen?",
    },
    "de": {
        "notif.generic.checkin.title": "✅ Kurzer Check-in",
        "notif.generic.checkin.body": "Irgendwelche Ausgaben heute? Tippe, um sie schnell zu erfassen.",
        "notif.generic.moneynotes.title": "Geldnotizen 💰",
        "notif.generic.moneynotes.body": "Am besten sofort nach dem Ausgeben erfassen. Zweitbestes? Jetzt.",
        "notif.generic.dontforget.title": "🔔 Nicht vergessen",
        "notif.generic.dontforget.body": "Kleine Gewohnheiten, große Klarheit. Nimm dir 30 Sekunden zum Erfassen.",
        "notif.generic.logday.title": "Tag erfassen 📋",
        "notif.generic.logday.body": "Dein zukünftiges Ich wird es dir danken. Etwas hinzufügen?",
        "notif.generic.stayontrack.title": "Auf Kurs bleiben 🎯",
        "notif.generic.stayontrack.body": "Den Überblick zu behalten dauert Sekunden. Dein Budget dankt dir.",
        "notif.generic.open.title": "Notyfi öffnen 👀",
        "notif.generic.open.body": "Erfasse die heutigen Ausgaben solange sie noch frisch sind.",
        "notif.generic.journaltime.title": "📝 Journal-Zeit",
        "notif.generic.journaltime.body": "Ein kurzer Eintrag jetzt spart viel Raten später.",
        "notif.generic.whatdidyouspend.title": "Was hast du ausgegeben? 🤔",
        "notif.generic.whatdidyouspend.body": "Deine Geldbörse erinnert sich an alles. Dein Gehirn nicht. Jetzt erfassen 👇",
        "notif.streak.days.title": "🔥 %d Tage in Folge",
        "notif.streak.consistent.body": "Du bist konsequent 💪 Halte die Serie heute am Leben.",
        "notif.streak.roll.title": "Auf dem Vormarsch 🚀",
        "notif.streak.roll.body": "%d Tage erfasst. Heute wird es %d.",
        "notif.budget.nearlygone.title": "Budget fast aufgebraucht ⚠️",
        "notif.budget.nearlygone.body": "%d%% verbraucht. Noch %@ diesen Monat übrig.",
        "notif.budget.almostover.title": "🚨 Fast über dem Budget",
        "notif.budget.almostover.body": "%@ übrig mit noch %d Tagen. Vorsicht.",
        "notif.budget.check.title": "Budget-Check 📊",
        "notif.budget.check.body": "%d%% diesen Monat verbraucht. %@ übrig über %d Tage.",
        "notif.budget.lookinggood.title": "Sieht gut aus 👍",
        "notif.budget.lookinggood.body": "%@ übrig mit %d Tagen. Du bist auf Kurs ✅",
        "notif.category.overtarget.title": "%@ über Ziel 📈",
        "notif.category.overtarget.body": "Du bist bei %d%% deines %@-Richtwerts diesen Monat.",
        "notif.category.almostcap.title": "⚡ %@ fast am Limit",
        "notif.category.almostcap.body": "%d%% des %@-Richtwerts verbraucht. %@ übrig.",
        "notif.savings.hit.title": "🎉 Sparziel erreicht!",
        "notif.savings.hit.body": "Du hast dein Sparziel diesen Monat erreicht. Gute Arbeit 🌟",
        "notif.savings.almost.title": "Fast am Sparziel 💪",
        "notif.savings.almost.body": "Nur noch %@ bis zum Ziel.",
        "notif.recurring.today": "heute",
        "notif.recurring.tomorrow": "morgen",
        "notif.recurring.indays": "in %d Tagen",
        "notif.recurring.title": "🔁 Bevorstehende Abbuchung %@",
        "notif.recurring.body": "%@ über %@ fällig %@.",
        "notif.weekly.title": "Letzte 7 Tage 📅",
        "notif.weekly.body": "Du hast %@ an Ausgaben in der letzten Woche erfasst.",
        "notif.missed.title": "😴 Gestern nicht erfasst",
        "notif.missed.body": "Nichts für gestern erfasst — möchtest du etwas aus dem Gedächtnis hinzufügen?",
    },
    "es": {
        "notif.generic.checkin.title": "✅ Revisión rápida",
        "notif.generic.checkin.body": "¿Algún gasto hoy? Toca para registrarlo mientras está fresco.",
        "notif.generic.moneynotes.title": "Notas de dinero 💰",
        "notif.generic.moneynotes.body": "El mejor momento para registrar es justo después de gastar. ¿El segundo mejor? Ahora.",
        "notif.generic.dontforget.title": "🔔 No olvides",
        "notif.generic.dontforget.body": "Pequeños hábitos, gran claridad. Toma 30 segundos para registrar hoy.",
        "notif.generic.logday.title": "Registra tu día 📋",
        "notif.generic.logday.body": "Tu yo futuro te lo agradecerá. ¿Algo que añadir?",
        "notif.generic.stayontrack.title": "Mantente en camino 🎯",
        "notif.generic.stayontrack.body": "Llevar el control toma segundos. Tu presupuesto te lo agradecerá.",
        "notif.generic.open.title": "Abrir Notyfi 👀",
        "notif.generic.open.body": "Captura los gastos de hoy mientras aún están frescos en tu mente.",
        "notif.generic.journaltime.title": "📝 Hora del diario",
        "notif.generic.journaltime.body": "Un registro rápido ahora ahorra mucho esfuerzo después.",
        "notif.generic.whatdidyouspend.title": "¿En qué gastaste? 🤔",
        "notif.generic.whatdidyouspend.body": "Tu cartera recuerda todo. Tu cerebro no. Registra ahora 👇",
        "notif.streak.days.title": "🔥 %d días seguidos",
        "notif.streak.consistent.body": "Has sido constante 💪 Mantén la racha viva hoy.",
        "notif.streak.roll.title": "En racha 🚀",
        "notif.streak.roll.body": "%d días registrando. Hoy serán %d.",
        "notif.budget.nearlygone.title": "Presupuesto casi agotado ⚠️",
        "notif.budget.nearlygone.body": "%d%% usado. Solo %@ restante este mes.",
        "notif.budget.almostover.title": "🚨 Casi sin presupuesto",
        "notif.budget.almostover.body": "%@ restante con %d días por delante. Ten cuidado.",
        "notif.budget.check.title": "Revisión de presupuesto 📊",
        "notif.budget.check.body": "Has usado %d%% este mes. %@ restante en %d días.",
        "notif.budget.lookinggood.title": "Buen ritmo 👍",
        "notif.budget.lookinggood.body": "%@ restante con %d días. Vas bien ✅",
        "notif.category.overtarget.title": "%@ sobre el objetivo 📈",
        "notif.category.overtarget.body": "Estás al %d%% de tu guía de %@ este mes.",
        "notif.category.almostcap.title": "⚡ %@ casi al límite",
        "notif.category.almostcap.body": "%d%% de tu guía de %@ usado. %@ restante.",
        "notif.savings.hit.title": "🎉 ¡Objetivo de ahorro alcanzado!",
        "notif.savings.hit.body": "Has alcanzado tu objetivo de ahorro este mes. Buen trabajo 🌟",
        "notif.savings.almost.title": "Casi en el objetivo de ahorro 💪",
        "notif.savings.almost.body": "Solo %@ para alcanzar tu objetivo.",
        "notif.recurring.today": "hoy",
        "notif.recurring.tomorrow": "mañana",
        "notif.recurring.indays": "en %d días",
        "notif.recurring.title": "🔁 Cargo próximo %@",
        "notif.recurring.body": "%@ por %@ vence %@.",
        "notif.weekly.title": "Últimos 7 días 📅",
        "notif.weekly.body": "Has registrado %@ en gastos durante la última semana.",
        "notif.missed.title": "😴 Ayer sin registrar",
        "notif.missed.body": "Nada registrado de ayer — ¿quieres añadir algo de memoria?",
    },
    "fi": {
        "notif.generic.checkin.title": "✅ Nopea tarkistus",
        "notif.generic.checkin.body": "Onko tänään menoja? Napauta kirjataksesi tuoreeltaan.",
        "notif.generic.moneynotes.title": "Rahamuistiinpanot 💰",
        "notif.generic.moneynotes.body": "Paras aika kirjata on heti kulutuksen jälkeen. Toiseksi paras? Nyt.",
        "notif.generic.dontforget.title": "🔔 Älä unohda",
        "notif.generic.dontforget.body": "Pienet tavat, suuri selkeys. Käytä 30 sekuntia kirjaamiseen tänään.",
        "notif.generic.logday.title": "Kirjaa päiväsi 📋",
        "notif.generic.logday.body": "Tuleva sinä kiittää. Jotain lisättävää?",
        "notif.generic.stayontrack.title": "Pysy raiteilla 🎯",
        "notif.generic.stayontrack.body": "Seuranta vie sekunteja. Budjettisi kiittää.",
        "notif.generic.open.title": "Avaa Notyfi 👀",
        "notif.generic.open.body": "Tallenna tämän päivän kulut kun ne ovat vielä tuoreessa muistissa.",
        "notif.generic.journaltime.title": "📝 Päiväkirja-aika",
        "notif.generic.journaltime.body": "Nopea kirjaus nyt säästää paljon arvailulta myöhemmin.",
        "notif.generic.whatdidyouspend.title": "Mitä käytit? 🤔",
        "notif.generic.whatdidyouspend.body": "Lompakkosi muistaa kaiken. Aivosi eivät. Kirjaa nyt 👇",
        "notif.streak.days.title": "🔥 %d päivää peräkkäin",
        "notif.streak.consistent.body": "Olet ollut johdonmukainen 💪 Pidä putki käynnissä tänään.",
        "notif.streak.roll.title": "Hyvässä vauhdissa 🚀",
        "notif.streak.roll.body": "%d päivää kirjattu. Tänään tulee %d.",
        "notif.budget.nearlygone.title": "Budjetti lähes lopussa ⚠️",
        "notif.budget.nearlygone.body": "%d%% käytetty. Enää %@ jäljellä tässä kuussa.",
        "notif.budget.almostover.title": "🚨 Lähes yli budjetin",
        "notif.budget.almostover.body": "%@ jäljellä, %d päivää jäljellä. Ole varovainen.",
        "notif.budget.check.title": "Budjettitarkistus 📊",
        "notif.budget.check.body": "Olet käyttänyt %d%% tässä kuussa. %@ jäljellä %d päivän ajan.",
        "notif.budget.lookinggood.title": "Näyttää hyvältä 👍",
        "notif.budget.lookinggood.body": "%@ jäljellä %d päivää. Olet oikealla tiellä ✅",
        "notif.category.overtarget.title": "%@ yli tavoitteen 📈",
        "notif.category.overtarget.body": "Olet %d%% %@-oppaastasi tässä kuussa.",
        "notif.category.almostcap.title": "⚡ %@ lähes rajalla",
        "notif.category.almostcap.body": "%d%% %@-oppaasta käytetty. %@ jäljellä.",
        "notif.savings.hit.title": "🎉 Säästötavoite saavutettu!",
        "notif.savings.hit.body": "Saavutit säästötavoitteesi tässä kuussa. Hienoa työtä 🌟",
        "notif.savings.almost.title": "Lähes säästötavoitteessa 💪",
        "notif.savings.almost.body": "Enää %@ tavoitteen saavuttamiseen.",
        "notif.recurring.today": "tänään",
        "notif.recurring.tomorrow": "huomenna",
        "notif.recurring.indays": "%d päivän päästä",
        "notif.recurring.title": "🔁 Tuleva veloitus %@",
        "notif.recurring.body": "%@ %@ erääntyy %@.",
        "notif.weekly.title": "Viimeiset 7 päivää 📅",
        "notif.weekly.body": "Olet kirjannut %@ kuluja viimeisen viikon aikana.",
        "notif.missed.title": "😴 Eilen kirjaamatta",
        "notif.missed.body": "Eilen ei kirjattu mitään — haluatko lisätä jotain muistista?",
    },
    "fr": {
        "notif.generic.checkin.title": "✅ Vérification rapide",
        "notif.generic.checkin.body": "Des dépenses aujourd'hui? Appuyez pour les noter pendant que c'est frais.",
        "notif.generic.moneynotes.title": "Notes financières 💰",
        "notif.generic.moneynotes.body": "Le meilleur moment pour noter, c'est juste après la dépense. Deuxième meilleur? Maintenant.",
        "notif.generic.dontforget.title": "🔔 N'oubliez pas",
        "notif.generic.dontforget.body": "Petites habitudes, grande clarté. Prenez 30 secondes pour noter aujourd'hui.",
        "notif.generic.logday.title": "Notez votre journée 📋",
        "notif.generic.logday.body": "Votre futur vous vous remerciera. Quelque chose à ajouter?",
        "notif.generic.stayontrack.title": "Restez sur la bonne voie 🎯",
        "notif.generic.stayontrack.body": "Suivre ses dépenses prend des secondes. Votre budget vous remerciera.",
        "notif.generic.open.title": "Ouvrir Notyfi 👀",
        "notif.generic.open.body": "Capturez les dépenses du jour pendant qu'elles sont encore fraîches.",
        "notif.generic.journaltime.title": "📝 Heure du journal",
        "notif.generic.journaltime.body": "Une note rapide maintenant évite beaucoup de suppositions plus tard.",
        "notif.generic.whatdidyouspend.title": "Qu'avez-vous dépensé? 🤔",
        "notif.generic.whatdidyouspend.body": "Votre portefeuille se souvient de tout. Pas votre cerveau. Notez maintenant 👇",
        "notif.streak.days.title": "🔥 %d jours d'affilée",
        "notif.streak.consistent.body": "Vous êtes régulier 💪 Gardez la série vivante aujourd'hui.",
        "notif.streak.roll.title": "Sur une lancée 🚀",
        "notif.streak.roll.body": "%d jours de notes. Aujourd'hui fait %d.",
        "notif.budget.nearlygone.title": "Budget presque épuisé ⚠️",
        "notif.budget.nearlygone.body": "%d%% utilisé. Seulement %@ restant ce mois.",
        "notif.budget.almostover.title": "🚨 Presque au-dessus du budget",
        "notif.budget.almostover.body": "%@ restant avec %d jours à tenir. Prudence.",
        "notif.budget.check.title": "Vérification du budget 📊",
        "notif.budget.check.body": "Vous avez utilisé %d%% ce mois. %@ restant sur %d jours.",
        "notif.budget.lookinggood.title": "Bonne allure 👍",
        "notif.budget.lookinggood.body": "%@ restant avec %d jours. Vous êtes dans les temps ✅",
        "notif.category.overtarget.title": "%@ au-dessus de l'objectif 📈",
        "notif.category.overtarget.body": "Vous êtes à %d%% de votre guide %@ ce mois.",
        "notif.category.almostcap.title": "⚡ %@ presque au plafond",
        "notif.category.almostcap.body": "%d%% de votre guide %@ utilisé. %@ restant.",
        "notif.savings.hit.title": "🎉 Objectif d'épargne atteint!",
        "notif.savings.hit.body": "Vous avez atteint votre objectif d'épargne ce mois. Bien joué 🌟",
        "notif.savings.almost.title": "Presque à l'objectif d'épargne 💪",
        "notif.savings.almost.body": "Plus que %@ pour atteindre votre objectif.",
        "notif.recurring.today": "aujourd'hui",
        "notif.recurring.tomorrow": "demain",
        "notif.recurring.indays": "dans %d jours",
        "notif.recurring.title": "🔁 Prélèvement à venir %@",
        "notif.recurring.body": "%@ de %@ est dû %@.",
        "notif.weekly.title": "7 derniers jours 📅",
        "notif.weekly.body": "Vous avez noté %@ en dépenses la semaine dernière.",
        "notif.missed.title": "😴 Hier non noté",
        "notif.missed.body": "Rien noté pour hier — voulez-vous ajouter quelque chose de mémoire?",
    },
    "it": {
        "notif.generic.checkin.title": "✅ Controllo veloce",
        "notif.generic.checkin.body": "Qualche spesa oggi? Tocca per registrarla mentre è fresca.",
        "notif.generic.moneynotes.title": "Note finanziarie 💰",
        "notif.generic.moneynotes.body": "Il momento migliore per registrare è subito dopo aver speso. Secondo migliore? Ora.",
        "notif.generic.dontforget.title": "🔔 Non dimenticare",
        "notif.generic.dontforget.body": "Piccole abitudini, grande chiarezza. Prenditi 30 secondi per registrare oggi.",
        "notif.generic.logday.title": "Registra la tua giornata 📋",
        "notif.generic.logday.body": "Il tuo io futuro ti ringrazierà. Qualcosa da aggiungere?",
        "notif.generic.stayontrack.title": "Rimani in carreggiata 🎯",
        "notif.generic.stayontrack.body": "Tenere traccia richiede secondi. Il tuo budget ti ringrazierà.",
        "notif.generic.open.title": "Apri Notyfi 👀",
        "notif.generic.open.body": "Cattura le spese di oggi finché sono ancora fresche nella mente.",
        "notif.generic.journaltime.title": "📝 Ora del diario",
        "notif.generic.journaltime.body": "Un rapido registro ora evita molte supposizioni dopo.",
        "notif.generic.whatdidyouspend.title": "Cosa hai speso? 🤔",
        "notif.generic.whatdidyouspend.body": "Il tuo portafoglio ricorda tutto. Il tuo cervello no. Registra ora 👇",
        "notif.streak.days.title": "🔥 %d giorni di fila",
        "notif.streak.consistent.body": "Sei stato costante 💪 Mantieni la serie viva oggi.",
        "notif.streak.roll.title": "In marcia 🚀",
        "notif.streak.roll.body": "%d giorni di registrazioni. Oggi diventa %d.",
        "notif.budget.nearlygone.title": "Budget quasi esaurito ⚠️",
        "notif.budget.nearlygone.body": "%d%% usato. Solo %@ rimasto questo mese.",
        "notif.budget.almostover.title": "🚨 Quasi fuori budget",
        "notif.budget.almostover.body": "%@ rimasto con %d giorni da andare. Attenzione.",
        "notif.budget.check.title": "Controllo budget 📊",
        "notif.budget.check.body": "Hai usato %d%% questo mese. %@ rimasto in %d giorni.",
        "notif.budget.lookinggood.title": "Buon andamento 👍",
        "notif.budget.lookinggood.body": "%@ rimasto con %d giorni. Sei sulla buona strada ✅",
        "notif.category.overtarget.title": "%@ sopra l'obiettivo 📈",
        "notif.category.overtarget.body": "Sei al %d%% della tua guida %@ questo mese.",
        "notif.category.almostcap.title": "⚡ %@ quasi al limite",
        "notif.category.almostcap.body": "%d%% della guida %@ usato. %@ rimasto.",
        "notif.savings.hit.title": "🎉 Obiettivo di risparmio raggiunto!",
        "notif.savings.hit.body": "Hai raggiunto il tuo obiettivo di risparmio questo mese. Ottimo lavoro 🌟",
        "notif.savings.almost.title": "Quasi all'obiettivo di risparmio 💪",
        "notif.savings.almost.body": "Solo %@ per raggiungere il tuo obiettivo.",
        "notif.recurring.today": "oggi",
        "notif.recurring.tomorrow": "domani",
        "notif.recurring.indays": "tra %d giorni",
        "notif.recurring.title": "🔁 Addebito imminente %@",
        "notif.recurring.body": "%@ di %@ scade %@.",
        "notif.weekly.title": "Ultimi 7 giorni 📅",
        "notif.weekly.body": "Hai registrato %@ in spese nell'ultima settimana.",
        "notif.missed.title": "😴 Ieri non registrato",
        "notif.missed.body": "Niente registrato per ieri — vuoi aggiungere qualcosa dalla memoria?",
    },
    "nl": {
        "notif.generic.checkin.title": "✅ Snelle check-in",
        "notif.generic.checkin.body": "Iets uitgegeven vandaag? Tik om het te loggen terwijl het vers is.",
        "notif.generic.moneynotes.title": "Geldnotities 💰",
        "notif.generic.moneynotes.body": "Het beste moment om te loggen is vlak na het uitgeven. Op een na beste? Nu.",
        "notif.generic.dontforget.title": "🔔 Vergeet niet",
        "notif.generic.dontforget.body": "Kleine gewoontes, grote duidelijkheid. Neem 30 seconden om vandaag te loggen.",
        "notif.generic.logday.title": "Log je dag 📋",
        "notif.generic.logday.body": "Je toekomstige zelf zal je dankbaar zijn. Iets toe te voegen?",
        "notif.generic.stayontrack.title": "Blijf op koers 🎯",
        "notif.generic.stayontrack.body": "Bijhouden duurt seconden. Je budget zal je dankbaar zijn.",
        "notif.generic.open.title": "Open Notyfi 👀",
        "notif.generic.open.body": "Leg de uitgaven van vandaag vast terwijl ze nog vers zijn.",
        "notif.generic.journaltime.title": "📝 Dagboektijd",
        "notif.generic.journaltime.body": "Een snelle log nu bespaart veel giswerk later.",
        "notif.generic.whatdidyouspend.title": "Wat heb je uitgegeven? 🤔",
        "notif.generic.whatdidyouspend.body": "Je portemonnee onthoudt alles. Je hersenen niet. Log nu 👇",
        "notif.streak.days.title": "🔥 %d dagen op rij",
        "notif.streak.consistent.body": "Je bent consistent geweest 💪 Houd de reeks vandaag in leven.",
        "notif.streak.roll.title": "Lekker bezig 🚀",
        "notif.streak.roll.body": "%d dagen gelogd. Vandaag wordt %d.",
        "notif.budget.nearlygone.title": "Budget bijna op ⚠️",
        "notif.budget.nearlygone.body": "%d%% gebruikt. Nog maar %@ over deze maand.",
        "notif.budget.almostover.title": "🚨 Bijna over budget",
        "notif.budget.almostover.body": "%@ over met %d dagen te gaan. Pas op.",
        "notif.budget.check.title": "Budgetcheck 📊",
        "notif.budget.check.body": "Je hebt %d%% gebruikt deze maand. %@ over in %d dagen.",
        "notif.budget.lookinggood.title": "Ziet er goed uit 👍",
        "notif.budget.lookinggood.body": "%@ over met %d dagen. Je bent op schema ✅",
        "notif.category.overtarget.title": "%@ boven doel 📈",
        "notif.category.overtarget.body": "Je zit op %d%% van je %@-gids deze maand.",
        "notif.category.almostcap.title": "⚡ %@ bijna op het maximum",
        "notif.category.almostcap.body": "%d%% van je %@-gids gebruikt. %@ over.",
        "notif.savings.hit.title": "🎉 Spaardoel bereikt!",
        "notif.savings.hit.body": "Je hebt je spaardoel deze maand bereikt. Goed gedaan 🌟",
        "notif.savings.almost.title": "Bijna op het spaardoel 💪",
        "notif.savings.almost.body": "Nog maar %@ om je doel te bereiken.",
        "notif.recurring.today": "vandaag",
        "notif.recurring.tomorrow": "morgen",
        "notif.recurring.indays": "over %d dagen",
        "notif.recurring.title": "🔁 Aankomende afschrijving %@",
        "notif.recurring.body": "%@ van %@ is verschuldigd %@.",
        "notif.weekly.title": "Afgelopen 7 dagen 📅",
        "notif.weekly.body": "Je hebt %@ aan uitgaven gelogd in de afgelopen week.",
        "notif.missed.title": "😴 Gisteren niet gelogd",
        "notif.missed.body": "Niets gelogd voor gisteren — wil je iets toevoegen uit het geheugen?",
    },
    "pl": {
        "notif.generic.checkin.title": "✅ Szybki przegląd",
        "notif.generic.checkin.body": "Jakieś wydatki dzisiaj? Dotknij, aby zapisać je na świeżo.",
        "notif.generic.moneynotes.title": "Notatki finansowe 💰",
        "notif.generic.moneynotes.body": "Najlepszy czas na zapisanie to zaraz po wydaniu. Drugi najlepszy? Teraz.",
        "notif.generic.dontforget.title": "🔔 Nie zapomnij",
        "notif.generic.dontforget.body": "Małe nawyki, duża jasność. Poświęć 30 sekund na zapisanie dzisiaj.",
        "notif.generic.logday.title": "Zapisz swój dzień 📋",
        "notif.generic.logday.body": "Twoje przyszłe ja będzie ci wdzięczne. Coś do dodania?",
        "notif.generic.stayontrack.title": "Trzymaj się planu 🎯",
        "notif.generic.stayontrack.body": "Śledzenie zajmuje sekundy. Twój budżet będzie ci wdzięczny.",
        "notif.generic.open.title": "Otwórz Notyfi 👀",
        "notif.generic.open.body": "Zapisz dzisiejsze wydatki, dopóki są jeszcze świeżo w pamięci.",
        "notif.generic.journaltime.title": "📝 Czas na dziennik",
        "notif.generic.journaltime.body": "Szybki zapis teraz oszczędza dużo zgadywania później.",
        "notif.generic.whatdidyouspend.title": "Na co wydałeś? 🤔",
        "notif.generic.whatdidyouspend.body": "Twój portfel pamięta wszystko. Twój mózg nie. Zapisz teraz 👇",
        "notif.streak.days.title": "🔥 %d dni z rzędu",
        "notif.streak.consistent.body": "Byłeś konsekwentny 💪 Utrzymaj serię przy życiu dzisiaj.",
        "notif.streak.roll.title": "Świetna passa 🚀",
        "notif.streak.roll.body": "%d dni zapisywania. Dzisiaj będzie %d.",
        "notif.budget.nearlygone.title": "Budżet prawie wyczerpany ⚠️",
        "notif.budget.nearlygone.body": "%d%% wykorzystane. Tylko %@ zostało w tym miesiącu.",
        "notif.budget.almostover.title": "🚨 Prawie przekroczony budżet",
        "notif.budget.almostover.body": "%@ zostało z %d dniami do końca. Uważaj.",
        "notif.budget.check.title": "Kontrola budżetu 📊",
        "notif.budget.check.body": "Wykorzystałeś %d%% w tym miesiącu. %@ pozostało na %d dni.",
        "notif.budget.lookinggood.title": "Wygląda dobrze 👍",
        "notif.budget.lookinggood.body": "%@ zostało z %d dniami. Jesteś na dobrej drodze ✅",
        "notif.category.overtarget.title": "%@ powyżej celu 📈",
        "notif.category.overtarget.body": "Jesteś na %d%% swojego przewodnika %@ w tym miesiącu.",
        "notif.category.almostcap.title": "⚡ %@ prawie przy limicie",
        "notif.category.almostcap.body": "%d%% przewodnika %@ wykorzystane. %@ zostało.",
        "notif.savings.hit.title": "🎉 Cel oszczędnościowy osiągnięty!",
        "notif.savings.hit.body": "Osiągnąłeś cel oszczędnościowy w tym miesiącu. Dobra robota 🌟",
        "notif.savings.almost.title": "Prawie przy celu oszczędnościowym 💪",
        "notif.savings.almost.body": "Tylko %@ do osiągnięcia celu.",
        "notif.recurring.today": "dzisiaj",
        "notif.recurring.tomorrow": "jutro",
        "notif.recurring.indays": "za %d dni",
        "notif.recurring.title": "🔁 Nadchodząca opłata %@",
        "notif.recurring.body": "%@ za %@ jest należne %@.",
        "notif.weekly.title": "Ostatnie 7 dni 📅",
        "notif.weekly.body": "Zarejestrowałeś %@ wydatków w ciągu ostatniego tygodnia.",
        "notif.missed.title": "😴 Wczoraj niezapisane",
        "notif.missed.body": "Nic nie zapisano za wczoraj — chcesz dodać coś z pamięci?",
    },
    "pt": {
        "notif.generic.checkin.title": "✅ Verificação rápida",
        "notif.generic.checkin.body": "Alguma despesa hoje? Toque para registrar enquanto está fresco.",
        "notif.generic.moneynotes.title": "Notas financeiras 💰",
        "notif.generic.moneynotes.body": "O melhor momento para registrar é logo após gastar. Segundo melhor? Agora.",
        "notif.generic.dontforget.title": "🔔 Não esqueça",
        "notif.generic.dontforget.body": "Pequenos hábitos, grande clareza. Reserve 30 segundos para registrar hoje.",
        "notif.generic.logday.title": "Registre seu dia 📋",
        "notif.generic.logday.body": "Seu eu futuro vai agradecer. Algo a acrescentar?",
        "notif.generic.stayontrack.title": "Fique no caminho 🎯",
        "notif.generic.stayontrack.body": "Acompanhar leva segundos. Seu orçamento vai agradecer.",
        "notif.generic.open.title": "Abrir Notyfi 👀",
        "notif.generic.open.body": "Capture os gastos de hoje enquanto ainda estão frescos na mente.",
        "notif.generic.journaltime.title": "📝 Hora do diário",
        "notif.generic.journaltime.body": "Um registro rápido agora poupa muito tempo depois.",
        "notif.generic.whatdidyouspend.title": "O que você gastou? 🤔",
        "notif.generic.whatdidyouspend.body": "Sua carteira lembra de tudo. Seu cérebro não. Registre agora 👇",
        "notif.streak.days.title": "🔥 %d dias seguidos",
        "notif.streak.consistent.body": "Você tem sido consistente 💪 Mantenha a sequência viva hoje.",
        "notif.streak.roll.title": "Em alta 🚀",
        "notif.streak.roll.body": "%d dias de registros. Hoje faz %d.",
        "notif.budget.nearlygone.title": "Orçamento quase esgotado ⚠️",
        "notif.budget.nearlygone.body": "%d%% utilizado. Apenas %@ restante este mês.",
        "notif.budget.almostover.title": "🚨 Quase sem orçamento",
        "notif.budget.almostover.body": "%@ restante com %d dias a decorrer. Cuidado.",
        "notif.budget.check.title": "Verificação de orçamento 📊",
        "notif.budget.check.body": "Você usou %d%% este mês. %@ restante em %d dias.",
        "notif.budget.lookinggood.title": "Boa trajetória 👍",
        "notif.budget.lookinggood.body": "%@ restante com %d dias. Você está no caminho certo ✅",
        "notif.category.overtarget.title": "%@ acima da meta 📈",
        "notif.category.overtarget.body": "Você está em %d%% do seu guia %@ este mês.",
        "notif.category.almostcap.title": "⚡ %@ quase no limite",
        "notif.category.almostcap.body": "%d%% do seu guia %@ utilizado. %@ restante.",
        "notif.savings.hit.title": "🎉 Meta de poupança atingida!",
        "notif.savings.hit.body": "Você atingiu sua meta de poupança este mês. Bom trabalho 🌟",
        "notif.savings.almost.title": "Quase na meta de poupança 💪",
        "notif.savings.almost.body": "Apenas %@ para atingir sua meta.",
        "notif.recurring.today": "hoje",
        "notif.recurring.tomorrow": "amanhã",
        "notif.recurring.indays": "em %d dias",
        "notif.recurring.title": "🔁 Débito pendente %@",
        "notif.recurring.body": "%@ de %@ vence %@.",
        "notif.weekly.title": "Últimos 7 dias 📅",
        "notif.weekly.body": "Você registrou %@ em despesas na última semana.",
        "notif.missed.title": "😴 Ontem não registrado",
        "notif.missed.body": "Nada registrado para ontem — quer adicionar algo da memória?",
    },
    "sv": {
        "notif.generic.checkin.title": "✅ Snabb incheckning",
        "notif.generic.checkin.body": "Några utgifter idag? Tryck för att logga medan det är färskt.",
        "notif.generic.moneynotes.title": "Penganoteringar 💰",
        "notif.generic.moneynotes.body": "Bästa tid att logga är direkt efter utgiften. Näst bäst? Nu.",
        "notif.generic.dontforget.title": "🔔 Glöm inte",
        "notif.generic.dontforget.body": "Små vanor, stor klarhet. Ta 30 sekunder för att logga idag.",
        "notif.generic.logday.title": "Logga din dag 📋",
        "notif.generic.logday.body": "Ditt framtida jag tackar dig. Något att lägga till?",
        "notif.generic.stayontrack.title": "Håll dig på kurs 🎯",
        "notif.generic.stayontrack.body": "Att ha koll tar sekunder. Din budget tackar dig.",
        "notif.generic.open.title": "Öppna Notyfi 👀",
        "notif.generic.open.body": "Fånga dagens utgifter medan de fortfarande är färska i minnet.",
        "notif.generic.journaltime.title": "📝 Dagbokstid",
        "notif.generic.journaltime.body": "En snabb logg nu sparar mycket gissande senare.",
        "notif.generic.whatdidyouspend.title": "Vad spenderade du? 🤔",
        "notif.generic.whatdidyouspend.body": "Din plånbok kommer ihåg allt. Din hjärna gör det inte. Logga nu 👇",
        "notif.streak.days.title": "🔥 %d dagar i rad",
        "notif.streak.consistent.body": "Du har varit konsekvent 💪 Håll serien vid liv idag.",
        "notif.streak.roll.title": "På rulle 🚀",
        "notif.streak.roll.body": "%d dagars loggning. Idag blir %d.",
        "notif.budget.nearlygone.title": "Budgeten nästan slut ⚠️",
        "notif.budget.nearlygone.body": "%d%% använt. Bara %@ kvar denna månad.",
        "notif.budget.almostover.title": "🚨 Nästan över budgeten",
        "notif.budget.almostover.body": "%@ kvar med %d dagar kvar. Var försiktig.",
        "notif.budget.check.title": "Budgetkontroll 📊",
        "notif.budget.check.body": "Du har använt %d%% denna månad. %@ kvar över %d dagar.",
        "notif.budget.lookinggood.title": "Ser bra ut 👍",
        "notif.budget.lookinggood.body": "%@ kvar med %d dagar. Du är på rätt väg ✅",
        "notif.category.overtarget.title": "%@ över målet 📈",
        "notif.category.overtarget.body": "Du är på %d%% av din %@-guide denna månad.",
        "notif.category.almostcap.title": "⚡ %@ nästan vid taket",
        "notif.category.almostcap.body": "%d%% av din %@-guide använt. %@ kvar.",
        "notif.savings.hit.title": "🎉 Sparmålet uppnått!",
        "notif.savings.hit.body": "Du har uppnått ditt sparmål denna månad. Bra jobbat 🌟",
        "notif.savings.almost.title": "Nästan vid sparmålet 💪",
        "notif.savings.almost.body": "Bara %@ kvar för att nå ditt mål.",
        "notif.recurring.today": "idag",
        "notif.recurring.tomorrow": "imorgon",
        "notif.recurring.indays": "om %d dagar",
        "notif.recurring.title": "🔁 Kommande debitering %@",
        "notif.recurring.body": "%@ på %@ förfaller %@.",
        "notif.weekly.title": "Senaste 7 dagarna 📅",
        "notif.weekly.body": "Du har loggat %@ i utgifter under den senaste veckan.",
        "notif.missed.title": "😴 I går inte loggat",
        "notif.missed.body": "Inget loggat för i går — vill du lägga till något från minnet?",
    },
}

base_dir = r"d:\Notyfi\Resources"

for lang_code, strings in translations.items():
    file_path = os.path.join(base_dir, f"{lang_code}.lproj", "Localizable.strings")
    block = "\n// Notification strings\n"
    for key, value in strings.items():
        block += f'"{key}" = "{value}";\n'
    with open(file_path, "a", encoding="utf-8") as f:
        f.write(block)
    print(f"Updated {lang_code}")

print("Done.")